apiVersion: apps/v1
kind: Deployment
metadata:
  name: mukulapp01
spec:
  selector:
    matchLabels:
      app: mukulapp01-pod
  template:
    metadata:
      labels:
        app: mukulapp01-pod
    spec:
      containers:
      - name: mukulapp01-container
        image: barclaysacr02.azurecr.io/mukulapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
