apiVersion: apps/v1
kind: Deployment
metadata:
  name: mukul-app01
spec:
  selector:
    matchLabels:
      app: mukul-app01
  template:
    metadata:
      labels:
        app: mukul-app01
    spec:
      containers:
      - name: mukul-app01-container
        image: barclaysacr02.azurecr.io/mukulapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
